filter:
    paths:
        - src/*
before_commands:
    - 'composer install --no-interaction --prefer-dist'
checks:
    php:
        code_rating: true
        duplication: false
tools:
    external_code_coverage: false
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs:
            - vendor
    php_cpd:
        enabled: true
        excluded_dirs:
            - vendor
